/* EKONOMI — VERSI A: ECONOMIC PULSE */
const EXAM_DURATION_MINUTES = 20;
const WARNING_THRESHOLD_SECONDS = 60;
const CLASS_OPTIONS = ["XII.1","XII.2","XII.3","XII.4","XII.5","XII.6","XII.7","XII.8","XII.9","XII.10","XII.11"];
const questions = [
{q:"Pertumbuhan ekonomi paling tepat menggambarkan perubahan...",options:["Kualitas lembaga politik","Jumlah penduduk miskin saja","Produksi barang dan jasa secara riil dari waktu ke waktu","Distribusi pendapatan antarwilayah saja","Jenis pajak yang dipungut negara"],answer:2,topic:"Pertumbuhan Ekonomi",explanation:"Pertumbuhan ekonomi menunjukkan peningkatan kapasitas produksi atau output barang dan jasa, umumnya diukur melalui kenaikan PDB riil dari waktu ke waktu."},
{q:"Peningkatan kualitas pendidikan, kesehatan, dan kesempatan kerja merupakan indikator utama...",options:["Pertumbuhan ekonomi semata","Neraca perdagangan","Pembangunan ekonomi","Kebijakan moneter","Nilai tukar"],answer:2,topic:"Pembangunan Ekonomi",explanation:"Pembangunan ekonomi memiliki cakupan lebih luas daripada pertumbuhan karena menilai perubahan kualitas hidup dan kesejahteraan masyarakat."},
{q:"Jika PDB riil suatu negara meningkat dari tahun ke tahun, tetapi ketimpangan dan pengangguran tetap tinggi, kesimpulan yang paling tepat adalah...",options:["Pertumbuhan ekonomi terjadi, tetapi pembangunan belum tentu merata","Negara pasti mengalami defisit APBN","Perdagangan internasional berhenti","Pajak otomatis turun","Inflasi pasti nol"],answer:0,topic:"Pertumbuhan & Pembangunan",explanation:"Kenaikan PDB riil menunjukkan pertumbuhan. Namun, pembangunan juga mempertimbangkan pemerataan, kesempatan kerja, kesehatan, pendidikan, dan kualitas hidup."},
{q:"Salah satu contoh transformasi ekonomi digital adalah...",options:["Membatasi transaksi hanya secara tunai","Marketplace yang mempertemukan penjual dan pembeli melalui platform digital","Menghapus seluruh kegiatan produksi","Melarang pembayaran elektronik","Mengurangi penggunaan teknologi dalam usaha"],answer:1,topic:"Ekonomi Digital",explanation:"Ekonomi digital memanfaatkan teknologi dan internet dalam aktivitas ekonomi. Marketplace adalah contoh nyata karena transaksi dan pertemuan penjual-pembeli berlangsung melalui platform digital."},
{q:"Keunggulan utama pembayaran digital bagi kegiatan ekonomi adalah...",options:["Selalu bebas risiko","Transaksi dapat dilakukan lebih cepat dan praktis","Tidak membutuhkan jaringan apa pun","Pasti menghilangkan semua biaya","Membuat semua harga menjadi sama"],answer:1,topic:"Ekonomi Digital",explanation:"Pembayaran digital dapat mempercepat transaksi, memudahkan pencatatan, dan meningkatkan kenyamanan. Namun, tetap ada risiko seperti keamanan data dan penipuan."},
{q:"Agar UMKM memperoleh manfaat dari digitalisasi secara berkelanjutan, langkah yang paling tepat adalah...",options:["Menghindari teknologi","Menggunakan platform digital sekaligus meningkatkan literasi dan keamanan digital","Hanya berjualan secara offline","Memberikan seluruh data akun kepada orang lain","Menghapus pencatatan keuangan"],answer:1,topic:"Ekonomi Digital",explanation:"Digitalisasi akan lebih bermanfaat jika disertai literasi digital, kemampuan mengelola keuangan, dan kesadaran terhadap keamanan data."},
{q:"APBN merupakan rencana keuangan tahunan pemerintah pusat yang ditetapkan dengan...",options:["Peraturan desa","Undang-undang","Keputusan perusahaan","Peraturan bank umum","Perjanjian dagang"],answer:1,topic:"APBN",explanation:"APBN adalah rencana keuangan tahunan pemerintahan negara yang disetujui DPR dan ditetapkan dengan undang-undang."},
{q:"Yang termasuk fungsi APBN sebagai alat untuk menjaga kestabilan perekonomian adalah fungsi...",options:["Stabilisasi","Administrasi perusahaan","Produksi rumah tangga","Konsumsi","Distribusi barang pribadi"],answer:0,topic:"APBN",explanation:"Fungsi stabilisasi APBN digunakan pemerintah untuk menjaga kestabilan ekonomi, misalnya melalui kebijakan penerimaan dan belanja negara."},
{q:"APBD ditetapkan melalui persetujuan bersama antara pemerintah daerah dengan...",options:["Bank Indonesia","BPK","DPRD","Kementerian Perdagangan","DPR RI"],answer:2,topic:"APBD",explanation:"Rancangan APBD dibahas dan disetujui bersama oleh pemerintah daerah dan DPRD sebelum ditetapkan menjadi APBD."},
{q:"Pajak yang dipungut atas penghasilan yang diterima atau diperoleh wajib pajak termasuk kelompok...",options:["Pajak penghasilan","Pajak daerah kendaraan","Bea meterai saja","Cukai","Pajak ekspor"],answer:0,topic:"Perpajakan",explanation:"Pajak Penghasilan (PPh) dikenakan atas penghasilan yang diterima atau diperoleh wajib pajak sesuai ketentuan perpajakan."},
{q:"Fungsi pajak yang berkaitan dengan pembiayaan pengeluaran negara disebut fungsi...",options:["Regulasi","Budgeter","Distribusi barang","Produksi","Konsumsi"],answer:1,topic:"Perpajakan",explanation:"Fungsi budgeter berarti pajak menjadi salah satu sumber penerimaan negara untuk membiayai berbagai pengeluaran pemerintah."},
{q:"Ketika pemerintah memberikan insentif pajak untuk mendorong investasi pada sektor tertentu, pajak sedang menjalankan fungsi...",options:["Budgeter saja","Regulerend atau mengatur","Konsumsi","Moneter","Produksi"],answer:1,topic:"Perpajakan",explanation:"Fungsi regulerend berarti pajak digunakan sebagai instrumen kebijakan untuk mengatur atau mendorong perilaku ekonomi tertentu."},
{q:"Jika nilai ekspor suatu negara lebih besar daripada nilai impornya dalam periode tertentu, kondisi tersebut menunjukkan...",options:["Defisit perdagangan","Surplus perdagangan","Inflasi otomatis","Defisit APBD","Resesi pasti"],answer:1,topic:"Ekonomi Internasional",explanation:"Surplus neraca perdagangan terjadi ketika nilai ekspor lebih besar daripada nilai impor. Jika impor lebih besar, kondisi tersebut disebut defisit."},
{q:"Kegiatan menjual barang dan jasa dari dalam negeri ke luar negeri disebut...",options:["Impor","Ekspor","Devaluasi","Subsidi","Proteksi"],answer:1,topic:"Ekonomi Internasional",explanation:"Ekspor adalah kegiatan menjual atau mengirim barang dan jasa dari suatu negara ke negara lain."},
{q:"Pemerintah mengenakan tarif impor untuk melindungi produsen dalam negeri. Kebijakan tersebut merupakan...",options:["Liberalisasi penuh","Proteksi perdagangan","Deregulasi moneter","Subsidi konsumsi","Kebijakan fiskal daerah"],answer:1,topic:"Ekonomi Internasional",explanation:"Tarif impor membuat barang dari luar negeri dikenai pungutan sehingga dapat melindungi produsen domestik dari persaingan impor yang terlalu kuat."}
];
